### ISSUE TITLE
La pelota se comporta impredeciblemente cuando se golpea verticalmente

### ISSUE THREAD

**Issue by alexdgs** [05K4R1N/Ping-Pong#3]
Pasos para reproducir:
1. Configurar la velocidad de la pelota a un valor bajo, menor a 1.0 (esto permitirá aprecir mejor el problema)
2. Esperar a que la pelota esta cerca a la meta de uno de los jugadores
3. Con el jugador cuya meta es amenazada golpear la pelota verticalmente, es decir, con los lados angostos del rectángulo del jugador.

Comportamiento actual:
La pelota se desplaza verticalmente "dentro" del rectángulo dle jugador como si se atascara en el mismo y, cuando la intersección cesa, toma un rumbo horizontal aleatorio (de vuelta al tablero o a la meta del jugador)

Comportameinto esperado
La pelota debería cambiar de dirección horizontal inmediatamente después de entrar en contacto con el jugador sin importar cuánto tiempo esté en contacto con el mismo

Aquí una imagen que ilustra el momento de la ocurrencia en cuestión
![pingpong_bug](https://cloud.githubusercontent.com/assets/7460734/19810467/9166a85c-9cfb-11e6-9544-effa14660968.png)

**Comment by DevLatBo** [comment]
La verdad te soy sincero, yo ya me habia dado cuenta ya antes, pero me parecia un efecto gracioso. xD
Mi planteamiento ante esta solucion es que si la pelota traspasa el limite del borde de la paletita de jugador X este pierde. Quiero decir con esto es que si la paletita no atrapa la pelota directamente pierde aunque este ya llegue un poco tarde. La pelotita entra dentro del area del rectangulo y sigue el juego, no deberia ser asi no ? aunque este llegue tarde, que sea partida perdida. No se si me deje endenter mmmm...

**Comment by alexdgs** [comment]
OK. Si ese es el comportamiento deseado entonces puede cerrar este issue.

**Comment by DevLatBo** [comment]
Estate atento a la siguiente actualizacon. ;) Saludos
